<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />

		<PackageReference Include="MudBlazor" Version="7.15.0" />
		<PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="8.0.2" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.2" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.2" PrivateAssets="all" />
		<PackageReference Include="itext7" Version="8.0.2" />
		<PackageReference Include="QuestPDF" Version="2025.12.3" />
		<PackageReference Include="SkiaSharp.NativeAssets.WebAssembly" Version="2.88.6" />
		<PackageReference Include="HarfBuzzSharp.NativeAssets.WebAssembly" Version="7.3.0" />
		<PackageReference Include="System.Text.Encoding.CodePages" Version="8.0.0" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EduSys.Shared\EduSys.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Components\" />
    <Folder Include="wwwroot\js\" />
  </ItemGroup>

</Project>
